// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AsideAuthor: typeof import('./src/components/AsideAuthor.vue')['default']
    AsideAuthorSkeleton: typeof import('./src/components/AsideAuthorSkeleton.vue')['default']
    AsideCard: typeof import('./src/components/AsideCard.vue')['default']
    AsideCardSkeleton: typeof import('./src/components/AsideCardSkeleton.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListArticle: typeof import('./src/components/listArticle.vue')['default']
    ListArticleSkeleton: typeof import('./src/components/ListArticleSkeleton.vue')['default']
    PageFooter: typeof import('./src/components/pageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    SkeletonCircle: typeof import('./src/components/skeleton/SkeletonCircle.vue')['default']
    SkeletonRect: typeof import('./src/components/skeleton/SkeletonRect.vue')['default']
  }
}

export { }
